import { tags as t } from '@lezer/highlight';
import { HighlightStyle } from "@codemirror/language";

export const lightHighlighting = HighlightStyle.define([
    { tag: t.keyword, color: '#1693d5' },
    { tag: [t.name, t.deleted, t.character, t.propertyName, t.macroName], color: '#ce9178' },
    { tag: [t.variableName], color: '#27478d' },
    { tag: [t.function(t.variableName)], color: '#92a308' },
    { tag: [t.labelName], color: '#81a1c1' },
    { tag: [t.color, t.constant(t.name), t.standard(t.name)], color: '#9cdcfe' },
    { tag: [t.definition(t.name)], color: '#a3be8c' },
    { tag: [t.brace, t.separator, t.operator, t.operatorKeyword], color: '#2d2d2d' },
    { tag: [t.annotation], color: '#d30102' },
    { tag: [t.number, t.changed, t.annotation, t.modifier, t.self, t.namespace], color: '#4e7b38' },
    { tag: [t.typeName, t.className], color: '#87bf49' },
    { tag: [t.tagName], color: '#b48ead' },
    { tag: [t.squareBracket], color: '#bf616a' },
    { tag: [t.angleBracket], color: '#ce9178' },
    { tag: [t.attributeName], color: '#ebcb8b' },
    { tag: [t.regexp], color: '#9cdcfe' },
    { tag: [t.quote], color: '#3b4252' },
    { tag: [t.string], color: '#ce9178' },
    {
        tag: t.link,
        color: '#8fbcbb',
        textDecoration: 'underline',
        textUnderlinePosition: 'under',
    },
    { tag: [t.url, t.escape, t.special(t.string)], color: '#ce9178' },
    { tag: [t.meta], color: '#88c0d0' },
    { tag: [t.comment], color: '#434c5e', fontStyle: 'italic' },
    { tag: t.strong, fontWeight: 'bold', color: '#9cdcfe' },
    { tag: t.emphasis, fontStyle: 'italic', color: '#9cdcfe' },
    { tag: t.strikethrough, textDecoration: 'line-through' },
    { tag: t.heading, fontWeight: 'bold', color: '#9cdcfe' },
    { tag: t.special(t.heading1), fontWeight: 'bold', color: '#9cdcfe' },
    { tag: t.heading1, fontWeight: 'bold', color: '#9cdcfe' },
    {
        tag: [t.heading2, t.heading3, t.heading4],
        fontWeight: 'bold',
        color: '#9cdcfe',
    },
    {
        tag: [t.heading5, t.heading6],
        color: '#9cdcfe',
    },
    { tag: [t.atom, t.bool, t.special(t.variableName)], color: '#ce9178' },
    {
        tag: [t.processingInstruction, t.inserted],
        color: '#8fbcbb',
    },
    { tag: [t.contentSeparator], color: '#ebcb8b' },
    { tag: t.invalid, color: '#434c5e', borderBottom: '1px dotted #d30102' },
])
export const darkHighlighting = HighlightStyle.define([
    {
        tag: [
            t.keyword,
            t.operatorKeyword,
            t.modifier,
            t.color,
            t.constant(t.name),
            t.standard(t.name),
            t.standard(t.tagName),
            t.special(t.brace),
            t.atom,
            t.bool,
            t.special(t.variableName),
        ],
        color: '#569cd6',
    },
    { tag: [t.controlKeyword, t.moduleKeyword], color: '#c586c0' },
    {
        tag: [
            t.name,
            t.deleted,
            t.character,
            t.macroName,
            t.propertyName,
            t.variableName,
            t.labelName,
            t.definition(t.name),
        ],
        color: '#4fc1ff',
    },
    { tag: t.heading, fontWeight: 'bold', color: '#4fc1ff' },
    {
        tag: [t.typeName, t.className, t.tagName, t.number, t.changed, t.annotation, t.self, t.namespace],
        color: '#4ec9b0',
    },
    { tag: [t.function(t.variableName), t.function(t.propertyName)], color: '#dcdcaa' },
    { tag: [t.number], color: '#b5cea8' },
    { tag: [t.operator, t.punctuation, t.separator, t.url, t.escape, t.regexp], color: '#d4d4d4' },
    { tag: [t.regexp], color: '#d16969' },
    { tag: [t.special(t.string), t.processingInstruction, t.string, t.inserted], color: '#ce9178' },
    { tag: [t.angleBracket], color: '#808080' },
    { tag: t.strong, fontWeight: 'bold' },
    { tag: t.emphasis, fontStyle: 'italic' },
    { tag: t.strikethrough, textDecoration: 'line-through' },
    { tag: [t.meta, t.comment], color: '#6a9955' },
    { tag: t.link, color: '#6a9955', textDecoration: 'underline' },
    { tag: t.invalid, color: '#ff0000' },
])